FROM alpine:3.5

RUN apk add --no-cache ca-certificates

ADD build/rancher-letsencrypt-linux-amd64 /usr/bin/rancher-letsencrypt
ADD lego/lego /usr/bin/lego 

RUN chmod +x /usr/bin/rancher-letsencrypt && chmod +x /usr/bin/lego

ENTRYPOINT ["/usr/bin/rancher-letsencrypt", "-debug", "-test-mode"]
EXPOSE 80
